### ISSUE TITLE
testing tools/frameworks

### ISSUE THREAD

**Issue by mishelashala** [getify/monio#1]
do you have any plan to add unit/integration tests?
If so, do you have any approach (bdd/tdd) or tool/framework (jest, mocha) on mind?

**Comment by getify** [comment]
Absolutely we need full unit tests. Definitely hoping to have some help with it! I always insist on my libraries having 100% test coverage for a 1.0 release. :)

I have always preferred qunit for simple unit testing, and istanbul (now called NYC) for code coverage. Here's an example of how I do it in another of my projects (CAF):

* https://github.com/getify/CAF/tree/master/tests ; AND
* https://github.com/getify/CAF/blob/master/scripts/node-tests.js

Ideally what I'd like is to get a small handful of tests put together and work out which lib and setup can be agreed on to work best, before go off and do the work to write a whole test suite for it.

----

ALSO, note... the current Monio code in index.js is going to be relocated into a subdirectory (likely `src`) and it's also going to be re-organized (either as a single UMD file, or a series of ESM modules, or something like that). So it's better if the test suite stays small (for now) so those kinds of changes can be incorporated more easily.

**Comment by getify** [comment]
FYI... the reorg has landed, so it should be a lot easier to start writing tests.

**Comment by mishelashala** [comment]
Thanks for the info, I'll take a look
