### ISSUE TITLE
Parallel IO Tasks

### ISSUE THREAD

**Issue by MalQaniss** [getify/monio#20]
If we let's say want to send parallel requests with "Promise.all" would this be a fine way:

```javascript
const planetsNums = ['1','2']
const getPlanet = num => IO(() => fetch(`https://swapi.dev/api/planets/${num}`).then(response => response.json()))

const data = await Promise.all([...planetsNums.map(num => getPlanet(num).run())])
console.log(data)

```

**Comment by getify** [comment]
Essentially, yes.

There's a helper in the `IOHelpers` module for this specific use-case, [called `waitAll(..)`](https://github.com/getify/monio/blob/83324b4f949817d264fb70a5bf6abe87acadb994/src/io/helpers.js#L92-L98). You'd use it in your example like this:

```js
const planetsNums = ['1','2']
const getPlanet = num => IO(() => fetch(`https://swapi.dev/api/planets/${num}`).then(response => response.json()))

const data= await waitAll( ...planetsNums.map(getPlanet) ).run();
console.log(data);
```
