### ISSUE TITLE
Free Monad

### ISSUE THREAD

**Issue by MalQaniss** [getify/monio#23]
Do you have any plans of adding Free Monad in the future?

**Comment by getify** [comment]
I'm basically aware of the `Free` monad, but not deeply cognizant of its applicability to Monio style code (with the IO, etc).

Can you give me an example where you'd like to use Free, perhaps alongside IO and/or the other monads in Monio?

If Monio had Free, what would that code look like in your preference?

If I can understand your intended uses, I can better speak to whether it makes sense to include in Monio. :)

**Comment by MalQaniss** [comment]
The only thing that comes to my mind now is for "trampolines", but that's a more general purpose tool I don't know if it would fit with Monio style. If I can find some others use-cases with IO, I will be sure to let you know.
